<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/8/25
 * Time: 16:00
 */

namespace rest\modules\v1\controllers;

use rest\modules\v1\actions\user\LoginAction;


/**
 * Class UserController
 * @package rest\modules\v1\controllers
 * @author 姜海强 <jhq0113@163.com>
 */
class UserController extends V1Controller
{
    /**
     * @return array
     * @author 姜海强 <jhq0113@163.com>
     */
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub

        $actions = array_merge($actions,[
            'login'=>[
                'class'         =>  LoginAction::class,
                'serviceClass'  =>  $this->serviceClass
            ]
        ]);

        return $actions;
    }
}