<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/8/25
 * Time: 16:00
 */

namespace rest\modules\v1\controllers;

use common\service\User;


/**
 * Class UserController
 * @package rest\modules\v1\controllers
 * @author 姜海强 <jhq0113@163.com>
 */
class UserController extends V1Controller
{
    /**
     * @var string   业务逻辑对象名称
     * @author 姜海强 <jhq0113@163.com>
     */
    public $serviceClass=User::class;

    /**
     * @return array
     * @author 姜海强 <jhq0113@163.com>
     */
    public function actions()
    {
        $actions=parent::actions();

        return array_merge($actions,[
            'login'=>[
                'class'         => 'rest\modules\v1\actions\user\LoginAction',
                'serviceClass'  =>  $this->serviceClass,
            ]
        ]);
    }

    /**
     * @return array
     * @author 姜海强 <jhq0113@163.com>
     */
    public function verbs()
    {
        $verbs=parent::verbs(); // TODO: Change the autogenerated stub
        return array_merge($verbs,[
            'login' => [ 'POST' ]
        ]);
    }
}