<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/8/25
 * Time: 16:00
 */

namespace rest\modules\v1\controllers;

use common\utils\ComHelper;
use rest\controllers\RestController;

/**
 * Class V1Controller
 * @package rest\modules\v1\controllers
 * @author 姜海强 <jhq0113@163.com>
 */
class V1Controller extends RestController
{
    /**
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     * @author 姜海强 <jhq0113@163.com>
     */
    public function afterAction($action, $result)
    {
        $result = parent::afterAction($action, $result); // TODO: Change the autogenerated stub

        if(is_array($result))
        {
            ComHelper::retArray($result);
        }

        return $result;
    }
}