<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/10/8
 * Time: 14:37
 */

namespace summer;


use summer\assets\SummerAssets;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\InputWidget;

/**
 * Class SummerWidget
 * @package summer
 * @author 姜海强 <jhq0113@163.com>
 */
class SummerWidget extends InputWidget
{
    /**
     * @var
     * @author 姜海强 <jhq0113@163.com>
     */
    public $summerOptions=[];

    /**服务器上传地址
     * @var string
     * @author 姜海强 <jhq0113@163.com>
     */
    public $uploadUrl='/up/summer';

    /**默认工具栏
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    private $_defaultToolbar= [
        ['style', ['codeview','style','bold', 'italic', 'underline', 'clear','undo','redo']],
        ['font', ['strikethrough', 'superscript', 'subscript']],
        ['fontsize', ['fontname','fontsize']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['height', ['height']],
        ['media',['link','picture','video']],
        ['table',['table']],
        ['addition',['fullscreen','help']]
    ];

    /**默认初始化配置
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    private $_defaultOptions=[
        'fontNames'=>[
            '宋体','微软雅黑','楷体','黑体','隶书',
            'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New', 'Helvetica Neue', 'Helvetica', 'Impact', 'Lucida Grande', 'Tahoma', 'Times New Roman', 'Verdana'
        ],
        'lang'=>'zh-CN'
    ];

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //编辑器id
        $id = isset($this->summerOptions['id']) ? $this->summerOptions['id'] : Html::getInputId($this->model, $this->attribute);

        $this->setId($id);

        $this->summerOptions = array_merge($this->_defaultOptions,$this->summerOptions);

        //工具栏
        $this->summerOptions['toolbar'] = isset($this->summerOptions['toolbar']) ? $this->summerOptions['toolbar'] : $this->_defaultToolbar;
    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        //注册脚本
        $this->registerAsset();

        return Html::activeTextarea($this->model, $this->attribute, ['id' => $this->id]);
    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    protected function registerAsset()
    {
        $summerAssets = SummerAssets::register($this->view);

        $script = $summerAssets->dealOptionsAndGetScript($this->view,$this->id,$this->summerOptions,$this->uploadUrl);

        $this->view->registerJs($script, View::POS_READY);
    }
}