<?php
/**
 * 角色控制器
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2016/12/3
 * Time: 10:54
 */

namespace backend\controllers;


use backend\service\AccessService;
use backend\service\MenuService;
use backend\service\RightService;
use backend\service\RoleService;
use common\utils\ComHelper;

class RoleController extends BackendController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->defaultService=RoleService::self();
    }

    public function actionIndex()
    {
        $list=RoleService::self()->getAll();
        return $this->render('index',['list'=>$list]);
    }

    /**添加
     * @return string
     * @author 姜海强 <jhq0113@163.com>
     */
    public function actionAdd()
    {
        if(\Yii::$app->request->isGet)
        {
            return $this->render('form');
        }
        elseif (isset($_POST['roleName'],$_POST['isOn']))
        {
            $item['roleName']=ComHelper::fStringP('roleName');
            $item['isOn']=ComHelper::fIntP('isOn');
            RoleService::self()->save($item);
            //清权限缓存
            MenuService::self()->delAllAdminMenu();
            ComHelper::retData();
        }
    }

    /**编辑
     * @return string
     * @author 姜海强 <jhq0113@163.com>
     */
    public function actionEdit()
    {
        if(isset($_GET['id']))
        {
            $id=ComHelper::fIntG('id');
            if($id>0)
            {
                $info=RoleService::self()->getInfo($id);
                if(!empty($info))
                {
                    return $this->render('form',['info'=>$info]);
                }
            }
        }
        elseif (isset($_POST['roleName'],$_POST['isOn'],$_POST['id']))
        {
            $item['roleName']=ComHelper::fStringP('roleName');
            $item['isOn']=ComHelper::fIntP('isOn');
            $item['id']=ComHelper::fIntP('id');
            RoleService::self()->save($item);
            //清权限缓存
            MenuService::self()->delAllAdminMenu();
            ComHelper::retData();
        }
    }

    /**给角色分配权限
     * @author 姜海强 <jhq0113@163.com>
     */
    public function actionAddRight()
    {
        if(isset($_GET['id'],$_GET['roleName']))
        {
            $roleId=ComHelper::fIntG('id');
            $roleName=ComHelper::fStringG('roleName');
            if($roleId>0)
            {
                $rightList=RightService::self()->getAllEnableList();

                if(!empty($rightList))
                {
                    $rightList=MenuService::rightListToMenu($rightList);
                }

                $ownList=AccessService::self()->getRightListByRoleIds([$roleId]);
                return $this->render(
                    'rights',
                    [
                        'list'=>$rightList,
                        'roleId'=>$roleId,
                        'roleName'=>$roleName,
                        'ownList'=>$ownList
                    ]
                );
            }
        }
        elseif (isset($_POST['roleId']))
        {
            $roleId=ComHelper::fIntP('roleId');
            $rightList=isset($_POST['rightList']) ? $_POST['rightList'] : [];
            AccessService::self()->save($roleId,$rightList);
            //清权限缓存
            MenuService::self()->delAllAdminMenu();
            ComHelper::retData();
        }

    }
}