<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/8/25
 * Time: 15:57
 */

namespace rest\controllers;


use common\base\IController;
use common\utils\ComHelper;
use yii\filters\ContentNegotiator;
use yii\filters\RateLimiter;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * Class RestController
 * @package rest\controllers
 * @author 姜海强 <jhq0113@163.com>
 */
class RestController extends IController
{
    /**禁用csrf验证
     * @var bool
     * @author 姜海强 <jhq0113@163.com>
     */
    public $enableCsrfValidation = false;

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function actionError()
    {
        ComHelper::retArray(['status'=>'404','message'=>'页面未找到']);
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     * @author 姜海强 <jhq0113@163.com>
     */
    public function behaviors()
    {
        return [
            'contentNegotiator' => [

                'class' => ContentNegotiator::className(),
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                ],
            ],
            'verbFilter' => [
                'class' => VerbFilter::className(),
                'actions' => $this->verbs(),
            ],
            'rateLimiter' => [
                'class' => RateLimiter::className(),
            ],
        ];
    }

    /**
     * @return array
     * @author 姜海强 <jhq0113@163.com>
     */
    public function actions()
    {
        return [
            'options' => [
                'class' => 'yii\rest\OptionsAction',
            ],
        ];
    }

    /**
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     * @author 姜海强 <jhq0113@163.com>
     */
    public function afterAction($action, $result)
    {
        $result = parent::afterAction($action, $result);
        if(isset($result) && is_array($result))
        {
            return $this->serializeData($result);
        }
    }

    /**
     * @return array
     * @author 姜海强 <jhq0113@163.com>
     */
    protected function verbs()
    {
        return [
            'options' => ['GET', 'HEAD'],
            'error' => ['GET', 'HEAD'],
        ];
    }

    /**
     * @param array $data
     * @return mixed
     * @author 姜海强 <jhq0113@163.com>
     */
    protected function serializeData($data)
    {
        ComHelper::retArray($data);
    }
}