<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/8/25
 * Time: 14:35
 */

namespace console\controllers;

use yii\console\Controller;

/**
 * Class BaseController
 * @package console\controllers
 * @author 姜海强 <jhq0113@163.com>
 */
class BaseController extends Controller
{
    /**脚本最大执行时间
     * @var int
     * @author 姜海强 <jhq0113@163.com>
     */
    public $timeLimit=300;

    /**当前时间戳
     * @var
     * @author 姜海强 <jhq0113@163.com>
     */
    public $time;

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->time     =   time();
    }

    /**写日志
     * @param string $message  消息内容
     * @author 姜海强 <jhq0113@163.com>
     */
    public function writeLog($message='')
    {
        $fileName=date('Y-m-d');
        $path=\Yii::getAlias('@console').'/runtime/logs/';
        if(!file_exists($path))
        {
            mkdir($path);
        }
        $fileName = $path.$fileName.'.log';
        $file=fopen($fileName,'a');
        if($file)
        {
            $message=date('Y-m-d H:i:s').' [    '.$message.'    ]'.PHP_EOL;
            fwrite($file,$message);
            fclose($file);
        }
    }
}