<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/8/25
 * Time: 14:34
 */

namespace console\controllers;


use console\models\popo\Task;

/**
 * Class TaskController
 * @package console\controllers
 * @author 姜海强 <jhq0113@163.com>
 */
class TaskController extends BaseController
{
    /**
     * @var Task
     * @author 姜海强 <jhq0113@163.com>
     */
    private $_task;

    /**校验秒级任务是否应该结束
     * @return bool
     * @author 姜海强 <jhq0113@163.com>
     */
    protected function checkSecondEnd()
    {
        return time() - $this->time >55;
    }

    /**执行秒级任务
     * @param callable  $callback     回调函数
     * @param int       $second       频率，最大为50，最小为1，默认10秒
     * @author 姜海强 <jhq0113@163.com>
     */
    public function executeSecondTask(callable $callback,$second=10)
    {
        $second = ($second > 50) ? 50 : $second;
        $second = ($second < 1)  ? 1  : $second;
        $num=0;
        while (true)
        {
            $num++;
            if($this->checkSecondEnd())
            {
                return;
            }

            $scriptStart = microtime(true);

            $this->writeLog("【{$this->id}/{$this->action->id}】[{$num}]");

            call_user_func($callback,$this);

            $span=microtime(true) - $scriptStart;

            $this->writeLog("--".$this->route.'['.$num.'] timeSpan:'.$span);

            $roundSpan=round($span);
            $step=$second -$roundSpan;
            $step = ($step < 1) ? 1 : $step;

            /**
             * 渐进式sleep
             */
            $result=$this->stepSleep($step);

            if(!$result)
            {
                return;
            }
        }
    }

    /**渐进式sleep
     * @param int $second    秒
     * @return bool
     * @author 姜海强 <jhq0113@163.com>
     */
    public function stepSleep($second)
    {
        if($second > 0)
        {
            for($s=0;$s < $second; $s++)
            {
                if($this->checkSecondEnd())
                {
                    return false;
                }
                sleep(1);
            }
        }
        return true;
    }

    /**
     * @param \yii\base\Action $action
     * @return bool
     * @author 姜海强 <jhq0113@163.com>
     */
    public function beforeAction($action)
    {
        $result=parent::beforeAction($action); // TODO: Change the autogenerated stub

        //记录日志
        $this->writeLog('   route:'.$this->route.'     --开始执行');

        //创建任务
        $this->_task = \Yii::createObject([
            'class' =>  Task::class,
            'route' =>  $this->route
        ]);

        //创建进程文件
        $this->_task->writeProcessId();

        return $result;
    }

    /**
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     * @author 姜海强 <jhq0113@163.com>
     */
    public function afterAction($action, $result)
    {
        $this->writeLog('   route:'.$this->route.'     --执行完毕');

        //删除进程文件
        $this->_task->deleteProcessId();

        exit();
    }
}