<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/8/25
 * Time: 16:02
 */

namespace rest\modules\v1\actions;


use common\base\IService;
use rest\exceptions\RestException;
use yii\base\Action;

/**
 * Class V1Action
 * @package rest\modules\v1\actions
 * @author 姜海强 <jhq0113@163.com>
 */
class V1Action extends Action
{
    /**
     * @var string
     * @author 姜海强 <jhq0113@163.com>
     */
    public $serviceClass;

    /**
     * @var IService
     * @author 姜海强 <jhq0113@163.com>
     */
    protected $service;

    /**
     * @return bool
     * @author 姜海强 <jhq0113@163.com>
     */
    public function beforeRun()
    {
        if(!isset($this->serviceClass))
        {
            throw new RestException('500',get_called_class().' : $serviceClass属性必须被赋值。');
        }

        //初始化Service
        $this->service = call_user_func([$this->serviceClass,'self'],[]);

        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function afterRun()
    {
        parent::afterRun(); // TODO: Change the autogenerated stub
    }
}