<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/10/11
 * Time: 18:04
 */

namespace common\widgets\upload;


use common\widgets\upload\assets\UploadAssets;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\InputWidget;

/**
 * Class IUploadWidget
 * @package common\widgets\upload
 * @author 姜海强 <jhq0113@163.com>
 */
abstract class IUploadWidget extends InputWidget
{
    /**
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    public $clientOptions=[];

    /**
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    protected $_defaultOptions=[
        'uploadUrl'=>'/up/upload'
    ];

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $id = isset($this->clientOptions['id']) ? $this->clientOptions['id'] : Html::getInputId($this->model, $this->attribute);
        $this->setId($id);

        $this->clientOptions = array_merge($this->_defaultOptions,$this->clientOptions);
    }

    /**
     * @return mixed
     * @author 姜海强 <jhq0113@163.com>
     */
    public function run()
    {
        parent::run();

        $this->registerAssets();

        return $this->getInputHtml();
    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function registerAssets()
    {
        UploadAssets::register($this->view);

        $script = '$(\'#' . $this->id .'\').bootstrapUpload('.json_encode($this->clientOptions).');';

        $this->view->registerJs($script, View::POS_READY);
    }

    /**
     * @return mixed
     * @author 姜海强 <jhq0113@163.com>
     */
    public function getInputHtml()
    {
        return Html::activeInput(
            'file',
                $this->model,
                $this->attribute,
                [
                    'id'            => $this->id,
                    'data-value'    =>  Html::getAttributeValue($this->model,$this->attribute)
                ]
        );
    }
}