<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/10/11
 * Time: 18:10
 */

namespace common\widgets\upload;


use common\utils\ComHelper;
use common\widgets\upload\utils\UploadHelper;
use yii\base\Action;

/**
 * Class UploadAction
 * @package common\widgets\upload
 * @author 姜海强 <jhq0113@163.com>
 */
class UploadAction extends Action
{
    /**上传目录
     * @var
     * @author 姜海强 <jhq0113@163.com>
     */
    public $uploadPath;

    /**url前缀
     * @var
     * @author 姜海强 <jhq0113@163.com>
     */
    public $urlPrefix;

    /**图片类型白名单
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    public $accessImageList =[
        'jpg','jpeg','png'
    ];

    /**视频类型白名单
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    public $accessVideoList =[
        'mp4'
    ];

    /**文件类型白名单
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    public $accessFileList  =[
        'pdf','zip','doc','xls','xlsx'
    ];

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->uploadPath = $this->uploadPath ? : \Yii::getAlias('@webroot/uploads');
        $this->urlPrefix  = $this->urlPrefix     ? : 'http://'.$_SERVER['HTTP_HOST'].'/uploads';
    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function run()
    {
        $file=UploadHelper::getFileByName('bootstrap-file');
        if(!$file)
        {
            exit(json_encode([
                'status'=>'404',
                'data'=>'请选择要上传的图片文件'
            ]));
        }

        $fileType = ComHelper::fStringP('fileType');
        switch ($fileType)
        {
            case 'image':
                exit(json_encode(UploadHelper::upImg($file,$this->uploadPath,$this->urlPrefix,$this->accessImageList)));
            case 'video':
                exit(json_encode(UploadHelper::upVideo($file,$this->uploadPath,$this->urlPrefix,$this->accessVideoList)));
            default:
                exit(json_encode(UploadHelper::upFile($file,$this->uploadPath,$this->urlPrefix,$this->accessFileList)));
        }
    }
}