<?php
/**
 * Created by PhpStorm.
 * User: 姜海强 <jhq0113@163.com>
 * Date: 2017/10/9
 * Time: 17:05
 */

namespace bootstrap_datetime_picker;


use bootstrap_datetime_picker\assets\DatetimePickerAssets;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\InputWidget;

/**
 * Class DatetimePickerWidget
 * @package bootstrap_datetime_picker
 * @author 姜海强 <jhq0113@163.com>
 */
class DatetimePickerWidget extends InputWidget
{
    /**配置
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    public $datetimePickerOptions=[];

    /**默认日期格式
     * @var array
     * @author 姜海强 <jhq0113@163.com>
     */
    private $_defaultOptions=[
        //'format'            =>  'yyyy-mm-dd',
        'format'            =>  'yyyy-mm-dd hh:ii:ss',
        'autoclose'         =>  true,
        'todayHighlight'    =>  true,
        'language'          =>  'zh-CN',
        'showMeridian'      =>  true,
    ];

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //datetimePicker id
        $id = isset($this->datetimePickerOptions['id']) ? $this->datetimePickerOptions['id'] : Html::getInputId($this->model, $this->attribute);

        $this->setId($id);

        $this->datetimePickerOptions = array_merge($this->_defaultOptions,$this->datetimePickerOptions);
    }

    /**
     * @return string
     * @author 姜海强 <jhq0113@163.com>
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $this->registerAsset();

        return Html::activeTextInput($this->model, $this->attribute,[
                                'id' => $this->id,
                                'size'=>16,
                                'class' => 'form-control'
            ]);

    }

    /**
     * @author 姜海强 <jhq0113@163.com>
     */
    protected function registerAsset()
    {
        $datetimePickerAssets = DatetimePickerAssets::register($this->view);

        $script               = $datetimePickerAssets->dealOptionsAndGetScript($this->view,$this->id,$this->datetimePickerOptions);

        $this->view->registerJs($script, View::POS_READY);
    }
}